#!/bin/bash

# HiC-Pro version 3.0.0

# Run HiC-Pro utility hicpro2juicebox.sh on HiC-Pro output to
# generate *.hic format matrix suitable for visualisation using Juicebox:

## hicpro2juicebox.sh --help
## Generate Juicebox input file from HiC-Pro results
## See http://www.aidenlab.org/juicebox/ for details about Juicebox
## ---------------
## OPTIONS
## 
##    -i|--input VALIDPAIRS : allValidPairs file generated by HiC-Pro >= 2.7.5
##    -g|--gsize GSIZE : genome size file used during HiC-Pro processing
##    -j|--jar JUICERJAR : path to juicebox_clt.jar file
##    [-r|--resfrag] RESFRAG : restriction fragment file used by HiC-Pro
##    [-t|--temp] TEMP : path to tmp folder. Default is current path
##    [-o|--out] OUT : output path. Default is current path
##    [-h|--help]: help
## 
## usage : hicpro2juicebox -i VALIDPAIRS -g GSIZE -j JUICERJAR [-r RESFRAG] [-t TEMP] [-o OUT] [-h]
## Use option -h|--help for more information

# Usage of HiC-Pro_hicpro2juicebox.sh:
# ./HiC-Pro_hicpro2juicebox.sh Col_0_HiC_HindIII_SRR1504819

SAMPLE=$1

source activate HiC_Pro

hicpro2juicebox.sh -i results/hic_results/data/${SAMPLE}/${SAMPLE}.allValidPairs \
                   -g T2T_Col.fa.sizes \
                   -j /applications/juicer/juicer-1.6/CPU/common/juicer_tools.jar \
                   -o results/hic_results/data/${SAMPLE}/ 

conda deactivate
